# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml

# Offense count: 2
Lint/UnderscorePrefixedVariableName:
  Exclude:
    - 'src/modules/FtpServer.rb'

# Offense count: 67
Metrics/AbcSize:
  Max: 268

# Offense count: 4
Metrics/BlockNesting:
  Max: 4

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 879

# Offense count: 11
Metrics/CyclomaticComplexity:
  Max: 115

# Offense count: 90
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 153

# Offense count: 79
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 479

# Offense count: 4
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 1051

# Offense count: 13
Metrics/PerceivedComplexity:
  Max: 150

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: braces, no_braces, context_dependent
Style/BracesAroundHashParameters:
  Exclude:
    - 'src/include/ftp-server/dialogs.rb'

# Offense count: 31
# Cop supports --auto-correct.
# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep, IndentationWidth.
# SupportedStyles: case, end
Style/CaseIndentation:
  Exclude:
    - 'src/include/ftp-server/write_load.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/ClosingParenthesisIndentation:
  Exclude:
    - 'src/modules/FtpServer.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/CommentIndentation:
  Exclude:
    - 'src/clients/ftp-server_auto.rb'

# Offense count: 12
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, SingleLineConditionsOnly.
# SupportedStyles: assign_to_condition, assign_inside_condition
Style/ConditionalAssignment:
  Exclude:
    - 'src/clients/ftp-server.rb'
    - 'src/include/ftp-server/wid_functions.rb'
    - 'src/include/ftp-server/write_load.rb'
    - 'src/modules/FtpServer.rb'

# Offense count: 9
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'src/clients/ftp-server.rb'
    - 'src/clients/ftp-server_auto.rb'
    - 'src/include/ftp-server/complex.rb'
    - 'src/include/ftp-server/dialogs.rb'
    - 'src/include/ftp-server/helps.rb'
    - 'src/include/ftp-server/wid_functions.rb'
    - 'src/include/ftp-server/wizards.rb'
    - 'src/include/ftp-server/write_load.rb'
    - 'src/modules/FtpServer.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowAdjacentOneLineDefs.
Style/EmptyLineBetweenDefs:
  Exclude:
    - 'src/clients/ftp-server.rb'

# Offense count: 116
# Cop supports --auto-correct.
Style/EmptyLines:
  Exclude:
    - 'src/clients/ftp-server.rb'
    - 'src/include/ftp-server/dialogs.rb'
    - 'src/include/ftp-server/helps.rb'
    - 'src/include/ftp-server/wid_functions.rb'
    - 'src/include/ftp-server/wizards.rb'
    - 'src/include/ftp-server/write_load.rb'
    - 'src/modules/FtpServer.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/EmptyLinesAroundMethodBody:
  Exclude:
    - 'src/include/ftp-server/wid_functions.rb'

# Offense count: 3
# Configuration parameters: ExpectMatchingDefinition, Regex, IgnoreExecutableScripts.
Style/FileName:
  Exclude:
    - 'src/clients/ftp-server.rb'
    - 'src/clients/ftp-server_auto.rb'
    - 'src/modules/FtpServer.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: consistent, special_for_inner_method_call, special_for_inner_method_call_in_parentheses
Style/FirstParameterIndentation:
  Exclude:
    - 'src/modules/FtpServer.rb'

# Offense count: 14
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'src/include/ftp-server/dialogs.rb'
    - 'src/include/ftp-server/write_load.rb'

# Offense count: 57
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
Style/HashSyntax:
  Exclude:
    - 'src/include/ftp-server/dialogs.rb'
    - 'src/include/ftp-server/wizards.rb'
    - 'src/modules/FtpServer.rb'

# Offense count: 2
Style/IdenticalConditionalBranches:
  Exclude:
    - 'src/clients/ftp-server.rb'

# Offense count: 7
Style/IfInsideElse:
  Exclude:
    - 'src/clients/ftp-server.rb'
    - 'src/include/ftp-server/write_load.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Exclude:
    - 'src/include/ftp-server/wid_functions.rb'
    - 'src/modules/FtpServer.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: special_inside_parentheses, consistent, align_brackets
Style/IndentArray:
  Exclude:
    - 'src/modules/FtpServer.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: Width.
Style/IndentationWidth:
  Exclude:
    - 'src/clients/ftp-server_auto.rb'

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: line_count_dependent, lambda, literal
Style/Lambda:
  Exclude:
    - 'src/include/ftp-server/wizards.rb'

# Offense count: 45
# Cop supports --auto-correct.
Style/LeadingCommentSpace:
  Exclude:
    - 'Rakefile'
    - 'src/clients/ftp-server.rb'
    - 'src/clients/ftp-server_auto.rb'
    - 'src/include/ftp-server/dialogs.rb'
    - 'src/include/ftp-server/wid_functions.rb'
    - 'src/modules/FtpServer.rb'

# Offense count: 94
# Cop supports --auto-correct.
Style/LineEndConcatenation:
  Exclude:
    - 'src/include/ftp-server/helps.rb'
    - 'src/include/ftp-server/wid_functions.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/MethodCallParentheses:
  Exclude:
    - 'src/modules/FtpServer.rb'

# Offense count: 168
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Style/MethodName:
  Exclude:
    - 'src/clients/ftp-server.rb'
    - 'src/include/ftp-server/complex.rb'
    - 'src/include/ftp-server/dialogs.rb'
    - 'src/include/ftp-server/helps.rb'
    - 'src/include/ftp-server/wid_functions.rb'
    - 'src/include/ftp-server/wizards.rb'
    - 'src/include/ftp-server/write_load.rb'
    - 'src/modules/FtpServer.rb'

# Offense count: 15
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: aligned, indented
Style/MultilineOperationIndentation:
  Exclude:
    - 'src/clients/ftp-server.rb'
    - 'src/clients/ftp-server_auto.rb'
    - 'src/include/ftp-server/helps.rb'
    - 'src/include/ftp-server/write_load.rb'
    - 'src/modules/FtpServer.rb'

# Offense count: 19
Style/MultilineTernaryOperator:
  Exclude:
    - 'src/include/ftp-server/write_load.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/MutableConstant:
  Exclude:
    - 'test/ftpserver_test.rb'

# Offense count: 5
# Cop supports --auto-correct.
Style/NegatedIf:
  Exclude:
    - 'src/include/ftp-server/complex.rb'
    - 'src/modules/FtpServer.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/NilComparison:
  Exclude:
    - 'src/include/ftp-server/wid_functions.rb'
    - 'src/modules/FtpServer.rb'

# Offense count: 32
# Cop supports --auto-correct.
# Configuration parameters: IncludeSemanticChanges.
Style/NonNilCheck:
  Exclude:
    - 'src/clients/ftp-server.rb'
    - 'src/modules/FtpServer.rb'

# Offense count: 4
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 9

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: predicate, comparison
Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'
    - 'src/include/ftp-server/wid_functions.rb'
    - 'src/include/ftp-server/write_load.rb'
    - 'src/modules/FtpServer.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Exclude:
    - 'src/include/ftp-server/complex.rb'
    - 'src/modules/FtpServer.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowAsExpressionSeparator.
Style/Semicolon:
  Exclude:
    - 'src/modules/FtpServer.rb'

# Offense count: 68
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment.
Style/SpaceAroundOperators:
  Exclude:
    - 'src/clients/ftp-server.rb'
    - 'src/include/ftp-server/helps.rb'

# Offense count: 2322
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'Rakefile'
    - 'src/clients/ftp-server.rb'
    - 'src/clients/ftp-server_auto.rb'
    - 'src/include/ftp-server/complex.rb'
    - 'src/include/ftp-server/dialogs.rb'
    - 'src/include/ftp-server/helps.rb'
    - 'src/include/ftp-server/wid_functions.rb'
    - 'src/include/ftp-server/wizards.rb'
    - 'src/include/ftp-server/write_load.rb'
    - 'src/modules/FtpServer.rb'
    - 'test/ftpserver_test.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiteralsInInterpolation:
  Exclude:
    - 'src/include/ftp-server/wid_functions.rb'
    - 'src/modules/FtpServer.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline, SupportedStyles.
# SupportedStyles: comma, consistent_comma, no_comma
Style/TrailingCommaInLiteral:
  Exclude:
    - 'src/clients/ftp-server.rb'

# Offense count: 16
# Cop supports --auto-correct.
Style/TrailingWhitespace:
  Exclude:
    - 'src/clients/ftp-server.rb'
    - 'src/clients/ftp-server_auto.rb'
    - 'src/modules/FtpServer.rb'

# Offense count: 20
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Style/VariableName:
  Exclude:
    - 'src/clients/ftp-server.rb'
    - 'src/include/ftp-server/helps.rb'
    - 'src/modules/FtpServer.rb'

# Offense count: 18
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles, MinSize, WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: brackets
